// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace CoronaStatisticsAPI.Migrations
{
    [DbContext(typeof(StatisticsContext))]
    internal class StatisticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CoronaStatisticsAPI.Model.CovidCases", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<int>("Cases")
                    .HasColumnType("int");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<int>("Deaths")
                    .HasColumnType("int");

                b.Property<int>("DistrictId")
                    .HasColumnType("int");

                b.Property<int>("Population")
                    .HasColumnType("int");

                b.Property<int>("SevenDaysIncidents")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("DistrictId");

                b.ToTable("CovidCases");
            });

            modelBuilder.Entity("CoronaStatisticsAPI.Model.District", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<int>("Code")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("StateId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("StateId");

                b.ToTable("Districts");
            });

            modelBuilder.Entity("CoronaStatisticsAPI.Model.FederalState", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("FederalStates");
            });

            modelBuilder.Entity("CoronaStatisticsAPI.Model.CovidCases", b =>
            {
                b.HasOne("CoronaStatisticsAPI.Model.District", "District")
                    .WithMany("Cases")
                    .HasForeignKey("DistrictId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("District");
            });

            modelBuilder.Entity("CoronaStatisticsAPI.Model.District", b =>
            {
                b.HasOne("CoronaStatisticsAPI.Model.FederalState", "State")
                    .WithMany("Districts")
                    .HasForeignKey("StateId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("State");
            });

            modelBuilder.Entity("CoronaStatisticsAPI.Model.District", b => { b.Navigation("Cases"); });

            modelBuilder.Entity("CoronaStatisticsAPI.Model.FederalState", b => { b.Navigation("Districts"); });
#pragma warning restore 612, 618
        }
    }
}